Import("*")

SimObject(
    "AIMCtrl.py",
    sim_objects=[
        "AIMCtrl",
        "AESUnit",
        "MACUnit",
        "IntTRB",
    ],
)

Source("aim_ctrl.cc")
Source("aes_unit.cc")
Source("mac_unit.cc")
Source("int_tree.cc")

DebugFlag("AIMCtrl", "Intermediating unit for various AIM operations")
DebugFlag("AESUnit", "Unit providing AES timing")
DebugFlag("MACUnit", "Unit providing MAC timing")
DebugFlag("IntTRB", "Unit storing in-flight tree update requests")
